from .CharacterAttacker import RandomCharacterAttacker
from .CharacterAttacker import UnsupervisedAdversarialCharacterAttacker
from .CharacterAttacker import SupervisedAdversarialCharacterAttacker

from .WordAttacker import RandomWordAttacker